### ISSUE TITLE
Security Issue - Phishing : User passwords Logged as JSON/*name file

### ISSUE THREAD

**Issue by ashindiano** [OpenGdg/source#1]
On a successful signup a user's complete detail including Password is being is stored in a file named with the user's name under JSON folder . This source code will create a Phishing site (if hosted) until that particular piece of PHP code is removed from /api/v1/authentication.php in the signup section

**Comment by prasanthp96** [comment]
Hy @facetheash . Thanks for pointing this out :) We have started with a new structure for the website from the scratch. So stay in touch :)

**Comment by ashindiano** [comment]
However the issue with this code still remains... Just so you guys know, It is illegal to store a user's password without being hashed and without the user's consent.
